import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Zilla_Slab, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LocationProvider } from "@/contexts/location-provider";
import { ConvexClientProvider } from "@/components/convex-provider";

const zillaSlab = Zilla_Slab({
  variable: "--font-zilla-slab",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <LocationProvider>
        <ConvexClientProvider>
          <html lang="en">
            <body
              className={`${zillaSlab.variable} ${geistMono.variable} antialiased`}
            >
              {children}
            </body>
          </html>
        </ConvexClientProvider>
      </LocationProvider>
    </ClerkProvider>
  );
}
